### ISSUE TITLE
Дюп предметов

### ISSUE THREAD

**Issue by Artem-VV** [SawFowl/GuiShopManager#13]
Из всех меню плагина можно забирать в инвентарь предметы при помощи зажатой кнопки Ctrl.
Версия плагина 1.0.4-S7.3
![image](https://github.com/SawFowl/GuiShopManager/assets/121773727/0d976141-053a-4fc7-9387-664f6e8c3315)
![image](https://github.com/SawFowl/GuiShopManager/assets/121773727/3b3f4436-63de-4b23-8bcf-663e13488895)

**Comment by SawFowl** [comment]
Я проверил и это не баг плагина. На SpongeForge без других модов такого не происходит. Проверяйте свою сборку. Что-то не дает отменить эвент. Задать приоритет прослушки эвента в кастомном инвентаре не представляется возможным.
![image](https://github.com/SawFowl/GuiShopManager/assets/29023558/b42dacf2-ea42-44a4-a27a-14f5ff5880ff)

**Comment by Artem-VV** [comment]
Проблема была в InventoryTweaks, сейчас все ок. Спасибо за помощь.
