### ISSUE TITLE
Sales error

### ISSUE THREAD

**Issue by ryryry11112** [SawFowl/GuiShopManager#2]
It is in use with the Pixelmon mode, but if you sell an item, there is no problem when you purchase it, but when you sell it, you enter how many numbers or only one item is sold, and the entered item disappears. Even if you sell 64, you only get 1 sale and 64 items disappear.

**Comment by SawFowl** [comment]
I will check in the near future as the plugin behaves with Pixelmon. With other modes, I did not notice the problem. Write down the video with a bug playback process if not difficult.

**Comment by SawFowl** [comment]
Fixed. See the latest release on the [ORE](https://ore.spongepowered.org/Semenkovsky_Ivan/GuiShopManager/versions).
