### ISSUE TITLE
Duplicated

### ISSUE THREAD

**Issue by WkaWkqhr** [SawFowl/GuiShopManager#3]
If you click on the sale several times quickly, it will be sold in duplicate from 2 to 4.
For example, even if there is one 
![image](https://user-images.githubusercontent.com/70570196/124694911-243daf00-df1d-11eb-8c05-81ead7a6e8c9.png)
set, if it is sold twice, it is sold twice as one set.

**Comment by SawFowl** [comment]
I'll try to figure it out. However, this appears to be an inventory bug in Sponge.

**Comment by SawFowl** [comment]
Try this version. I don't have my own server, so I can't check. And since the ping on the localhost is minimal, I will not be able to catch this bug.

[GuiShopManager-1.0.3.zip](https://github.com/SawFowl/GuiShopManager/files/6775220/GuiShopManager-1.0.3.zip)

**Comment by WkaWkqhr** [comment]
I tested it on the localhost server and it's the same.
If you hit sales very fast and multiple times, the same thing happens.
I used the new version you gave me.
![image](https://user-images.githubusercontent.com/70570196/124725190-a4790a00-df47-11eb-97ed-8976e0c2b592.png)

**Comment by WkaWkqhr** [comment]
https://drive.google.com/file/d/1Xn4iTd-lg4Q-irRWlGmNI2P4OXAdDdB-/view?usp=sharing

**Comment by SawFowl** [comment]
I'll try to think of something else.

**Comment by SawFowl** [comment]
Try this. At the moment, I have no opportunity to test it myself, since I am at work.
[GuiShopManager-1.0.3.zip](https://github.com/SawFowl/GuiShopManager/files/6776168/GuiShopManager-1.0.3.zip)

**Comment by SawFowl** [comment]
Try this. At the moment, I have no opportunity to test it myself, since I am at work.
[GuiShopManager-1.0.3.zip](https://github.com/SawFowl/GuiShopManager/files/6776204/GuiShopManager-1.0.3.zip)

**Comment by WkaWkqhr** [comment]
I think it's fixed.
Thank you.

**Comment by SawFowl** [comment]
Thanks for the bug report.

**Comment by SawFowl** [comment]
I recommend downloading the last release with the ORE. Everything is fixed there.
