### ISSUE TITLE
The Shops dissapears after server restart

### ISSUE THREAD

**Issue by kriticalvinho** [SawFowl/GuiShopManager#5]
When i restart the server the shops dissapears from the game. In the shops file still are the shops, when i reload the plugin for try fix it, console says:
Input 'totaleconomy:dollar' was not a valid value for type org.spongepowered.api.service.economy.Currency

sorry for my bad english

**Comment by SawFowl** [comment]
What version of Sponge do you have?

**Comment by kriticalvinho** [comment]
spongeforge-1.12.2-2838-7.3.0.jar

**Comment by SawFowl** [comment]
It's strange. It shouldn't be like that. You have something with the order in which the plugins are loaded.

**Comment by kriticalvinho** [comment]
I think no, because i reinstall the plugins and have the same issue when i create any shop, at restart the server. I gonna reinstall all plugins with diferent order to try fix It.

**Comment by SawFowl** [comment]
This should not be the case, because the loading of store and auction data occurs at the final stage of the server launch. At this stage, all currencies must already be registered.
https://github.com/SawFowl/GuiShopManager/blob/f1c2ebd2d22fdfbbc7237dc368ca1a94d9a991e3/src/main/java/sawfowl/guishopmanager/GuiShopManager.java#L310
Perhaps your economy plugin is not configured correctly.

**Comment by kriticalvinho** [comment]
With the economy plugin predetermined .config doesn't work too..
I create the shop with predetermined econmy and restart the server but still the issue

**Comment by SawFowl** [comment]
Upload your shop and economy config files. I'll check everything in the evening.

**Comment by kriticalvinho** [comment]
GuiShop .Config:
[https://pastebin.com/raw/mvvWwSue](https://pastebin.com/raw/mvvWwSue)
Shop Example:
[https://pastebin.com/raw/bFNLMCy9](https://pastebin.com/raw/bFNLMCy9)
TotalEconomy .Config:
[https://pastebin.com/raw/rMYi2Zdw](https://pastebin.com/raw/rMYi2Zdw)

i try reinstalling the plugins with diferent order, but i cant fix it

**Comment by SawFowl** [comment]
I used your configuration files and did not see problems.
![screenshot](https://user-images.githubusercontent.com/29023558/133832132-102779fd-8211-4461-8279-aba77465dc6e.png)

**Comment by kriticalvinho** [comment]
all works good, the problem is when i restart the server, all disapear

In game says: there are no shop created contact with the admins

and the console say the same:
Input 'totaleconomy:calvin' was not a valid value for type org.spongepowered.api.service.economy.Currency

**Comment by SawFowl** [comment]
I did a few restarts, but I do not see the problems. Everything works. Do you have a Discord? Show me on video.

SawFowl#2587

**Comment by kriticalvinho** [comment]
Yes i add u say me something when you can
