### ISSUE TITLE
OutOfMemory Errors

### ISSUE THREAD

**Issue by Drathonix** [SawFowl/GuiShopManager#7]
To anyone on the internet who is unfortunate enough to have downloaded this plugin and is experiencing OutOfMemory errors, this plugin is at fault.

There is a serious mistake in the code of this plugin that causes OutOfMemory errors after a few hours of running.

**In the API-7 version of GuiShopManager,** there is an issue where the plugin schedules a task on an interval of 55 seconds, inside of this task, another task is scheduled on an interval of 5 seconds. This means that the plugin continuously schedules tasks that can never end and eventually, this overloads the SpongeForge async scheduler.
This is the code, found in the plugin class.
```
updateAuctionTask = Task.builder().async().interval(55, TimeUnit.SECONDS).execute(() -> {
                workAuctionData.loadAuction();
                Task.builder().async().interval(5, TimeUnit.SECONDS).execute(() -> {
 ```

**In the API-8 version of the plugin the problem has been patched, the second task has been put on a delay which is what was the correct thing to do.**

For reference on how this plugin affects your server, this is the number of running tasks for every plugin running after about 40 minutes:

**Async Tasks**
WorldEdit: 0 tasks
UniverseGuard: 0 tasks
SpongeForge: 0 tasks
GriefDefender: 0 tasks
Donation Store: 1 tasks
REDACTED (Custom server plugin): 1 tasks
HuskyCrates: 1 tasks
Prism: 1 tasks
CatClearLag: 2 tasks
BungeeTabListPlus-SpongeBridge: 3 tasks
Nucleus: 6 tasks
Plan: 7 tasks
LuckPerms: 8 tasks
**GuiShopManager:** 31 tasks

Its a slow process but once the tasks reaches a certain count, the server will freeze up and no longer respond to user input. Even restarting the server is impossible (you'll have to kill the program and start it up again).

The error (Just so this shows up in searches more often):
java.lang.OutOfMemoryError: unable to create new native thread

**Comment by SawFowl** [comment]
This is an odd problem. No one whom I gave the plugin to test has complained. But if the problem still occurs, I will try to change this part of the code in the near future. I will try to think of something better.

**Comment by Drathonix** [comment]
> This is an odd problem. No one whom I gave the plugin to test has complained. But if the problem still occurs, I will try to change this part of the code in the near future. I will try to think of something better.

It's a problem that occurs after many hours of running. I've been running my server for about 10 hours now and your plugin has 663 tasks in the async task manager. Its really unnoticeable unless you don't restart the server. As I've said, you've patched it in the API-8 ver

The only way I could detect that it was your plugin causing the problem was by custom coding a debug tool to print out the Sponge async manager contents every few minutes.

**Comment by SawFowl** [comment]
This seems to be a problem with Sponge itself, since the code in the two versions of the plugin is generally similar. However, I'll try to find another solution, maybe do something similar to what you can see in the TotalEconomy plugin. I liked the idea implemented in the TotalEconomy plugin, although I did not understand how it was implemented.
The only difference in updating data between versions is that the API of the schedulers has changed. Everything else about the update method is basically the same.

**Comment by Drathonix** [comment]
> This seems to be a problem with Sponge itself, since the code in the two versions of the plugin is generally similar. However, I'll try to find another solution, maybe do something similar to what you can see in the TotalEconomy plugin. I liked the idea implemented in the TotalEconomy plugin, although I did not understand how it was implemented. The only difference in updating data between versions is that the API of the schedulers has changed. Everything else about the update method is basically the same.

I feel like you're not getting me. This is only partially Sponge's problem, there needs to be a safe guard for the mistake you made.

This is what I'm trying to point out to you:
**In API 7 you wrote**
```
updateAuctionTask = Task.builder().async().interval(55, TimeUnit.SECONDS).execute(() -> {
                workAuctionData.loadAuction();
                Task.builder().async()**.interval**(5, TimeUnit.SECONDS).execute(() -> {
``` 
**In API 8 you wrote**
```
updateAuctionTask = Task.builder().async().interval(55, TimeUnit.SECONDS).execute(() -> {
                workAuctionData.loadAuction();
                Task.builder().async().**delay**(5, TimeUnit.SECONDS).execute(() -> {
```
When you write something to execute on INTERVAL when the code completes, SpongeForge doesn't remove the task from the Scheduler which is what is supposed to happen. After the time has passed the code executes again.

Since you put an INTERVAL INSIDE AN INTERVAL you have basically created an infinite loop where you keep scheduling tasks that can't be removed from the scheduler. This fills up the scheduler. Once the scheduler gets filled up, Sponge can't schedule its own tasks which means your server is effectively frozen.

In the API-8 version you put a DELAY INSIDE AN INTERVAL. The delay means that the code will execute after the delay has passed and Sponge will remove it from the scheduler. 
**So in API-8, every 55 seconds you schedule something to run 5 seconds later. Sponge executes and removes the task 5 seconds later. This is totally fine**
**In API-7, every 55 seconds you schedule something to run on an interval of 5 seconds. So every 5 seconds, Sponge executes the task but does not remove it. This is bad.**

Sponge is not at fault. You are.
The only problem Sponge has is that it doesn't have any sort of detection system for Scheduler overflow and instead causes the server to freeze up.

**Comment by SawFowl** [comment]
Oh shit. I guess I'm blind and didn't notice how I accidentally chose the wrong method myself... 
I'll fix that in a minute.  Thank you.

**Comment by SawFowl** [comment]
Done. You can check it out. I also applied a few changes from the test branch.

**Comment by Drathonix** [comment]
> Done. You can check it out. I also applied a few changes from the test branch.

Awesome Thanks for solving this problem.
